#### R examples

#### R Programming
* [www.r-project](http://www.r-project.org/)
* [R project for statistical computing](http://journal.r-project.org/)
* [R-bloggers: news and tutorials about R](http://www.r-bloggers.com/)
* [Rseek.org](http://rseek.org/)
* [Stack Overflow R discussions](http://stackoverflow.com/questions/tagged/r)
* [R Programming Wikibook](http://en.wikibooks.org/wiki/R_Programming)

#### Google's R Style Guide
* [Google's R Style Guide](http://google-styleguide.googlecode.com/svn/trunk/Rguide.xml)

#### RStudio
* [RStudio](http://www.rstudio.com/)
* [RStudio Support](https://support.rstudio.com/hc/en-us)
* [RStudio Documentation](https://support.rstudio.com/hc/en-us/categories/200035113-Documentation)

#### Markdown
* [Using Equations with Markdown](http://www.rstudio.com/ide/docs/authoring/using_markdown_equations)
* [Markdown wiki](http://ru.wikipedia.org/wiki/Markdown)
* [Using Markdown with RStudio](http://www.rstudio.com/ide/docs/authoring/using_markdown)

#### R Color Chart
* [R Color Chart](http://research.stowers-institute.org/efg/R/Color/Chart/)

#### Try R
* [Try R Chapter 0](Try R Chapter 0.html). Install packages
* [Try R Chapter 1](Try R Chapter 1.html). Help
* [Try R Chapter 2](Try R Chapter 2.html). Vectors
* [Try R Chapter 3](Try R Chapter 3.html). Matrices
* [Try R Chapter 4](Try R Chapter 4.html). Summary Statistics
* [Try R Chapter 5](Try R Chapter 5.html). Factors
* [Try R Chapter 6](Try R Chapter 6.html). Files
* [Try R Chapter 7](Try R Chapter 7.html). Data Frames

#### Some Real World Samples
* [Samples R 0](Samples R 0.html). Trouble solutions
* [Samples R 1](Samples R 1.html). Install packages
* [Samples R 2](Samples R 2.html). DateTime POSIXct
* [Samples R 3](Samples R 3.html). rCharts add assets such as CSS and JS libraries  

#### Up and Running with R
* [Example R 03_01](Up and Running with R/Example R 03_01.html). Creating bar charts
* [Example R 03_02](Up and Running with R/Example R 03_02.html). Creating histograms
* [Example R 03_03](Up and Running with R/Example R 03_03.html). Creating box plots
* [Example R 03_04](Up and Running with R/Example R 03_04.html). Calculating frequencies
* [Example R 03_05](Up and Running with R/Example R 03_05.html). Calculating descriptives
* [Example R 04_01](Up and Running with R/Example R 04_01.html). Recoding variables
* [Example R 04_02](Up and Running with R/Example R 04_02.html). Computing new variables
* [Example R 05_01](Up and Running with R/Example R 05_01.html). Creating charts for group distributions
* [Example R 05_02](Up and Running with R/Example R 05_02.html). Creating scatterplots
* [Example R 05_03](Up and Running with R/Example R 05_03.html). Creating scatterplot matrices
* [Example R 05_04](Up and Running with R/Example R 05_04.html). Creating 3-D scatterplots
* [Example R 06_01](Up and Running with R/Example R 06_01.html). Calculating correlations
* [Example R 06_02](Up and Running with R/Example R 06_02.html). Computing a regression
* [Example R 06_03](Up and Running with R/Example R 06_03.html). Creating crosstabs
* [Example R 06_04](Up and Running with R/Example R 06_04.html). Comparing means with the t-test
* [Example R 06_05](Up and Running with R/Example R 06_05.html). Comparing means with ANOVA
* [Example R 07_01](Up and Running with R/Example R 07_01.html). Links