### Try R Chapter 2

## Vectors

### Пример
### Vectors
```{r}
c(4, 7, 9)
c('a', 'b', 'c')
c(1, TRUE, "three")
```

### Пример
### Sequence Vectors
```{r}
5:9
seq(5, 9)
seq(5, 9, 0.5)
9:5
```

### Пример
### Vector Access
```{r}
sentence <- c('walk', 'the', 'plank')
sentence

sentence[3]
sentence[1]
sentence[3] <- "dog"
sentence[4] <- 'to'
sentence

sentence[c(1, 3)]
sentence[2:4]
sentence[5:7] <- c('the', 'poop', 'deck')
sentence
```

### Пример
### Vector Names
```{r}
ranks <- 1:3
names(ranks) <- c("first", "second", "third")
ranks
ranks["first"]
ranks["third"] <- 4
ranks
```

### Пример
### Vector Math
```{r}
a <- c(1, 2, 3)
a + 1
a / 2
a*2
b <- c(4, 5, 6)
a + b
a-b
a == c(1, 99, 3)
a < b
sin(a)
sqrt(a)
```

### Пример
### NA Values
```{r}
a <- c(1, 3, NA, 7, 9)
sum(a)
help(sum)
sum(a, na.rm = TRUE)
```

### Пример
### Plotting One Vector
```{r}
vesselsSunk <- c(4, 5, 1)
barplot(vesselsSunk)
names(vesselsSunk) <- c("England", "France", "Norway")
barplot(vesselsSunk)

barplot(v<-1:10)
```

### Пример
### Scatter Plots
```{r}
x <- seq(1, 20, 0.1)
y <- sin(x)
plot(x, y)
#
values <- -10:10
absolutes <- abs(values)
plot(values, absolutes)
```