#### R examples

### R Links

#### R Programming
* [www.r-project](http://www.r-project.org/)
* [R project for statistical computing](http://journal.r-project.org/)
* [R-bloggers: news and tutorials about R](http://www.r-bloggers.com/)
* [Rseek.org](http://rseek.org/)
* [Stack Overflow R discussions](http://stackoverflow.com/questions/tagged/r)
* [R Programming Wikibook](http://en.wikibooks.org/wiki/R_Programming)

#### Google's R Style Guide
* [Google's R Style Guide](http://google-styleguide.googlecode.com/svn/trunk/Rguide.xml)

#### RStudio
* [RStudio](http://www.rstudio.com/)
* [RStudio Support](https://support.rstudio.com/hc/en-us)
* [RStudio Documentation](https://support.rstudio.com/hc/en-us/categories/200035113-Documentation)

#### Markdown
* [Using Equations with Markdown](http://www.rstudio.com/ide/docs/authoring/using_markdown_equations)
* [Markdown wiki](http://ru.wikipedia.org/wiki/Markdown)
* [Using Markdown with RStudio](http://www.rstudio.com/ide/docs/authoring/using_markdown)

#### R Color Chart
* [R Color Chart](http://research.stowers-institute.org/efg/R/Color/Chart/)

### Try R
* [Try R Chapter 0](Try R tutorial/Try R Chapter 0.html). Install packages
* [Try R Chapter 1](Try R tutorial/Try R Chapter 1.html). Help
* [Try R Chapter 2](Try R tutorial/Try R Chapter 2.html). Vectors
* [Try R Chapter 3](Try R tutorial/Try R Chapter 3.html). Matrices
* [Try R Chapter 4](Try R tutorial/Try R Chapter 4.html). Summary Statistics
* [Try R Chapter 5](Try R tutorial/Try R Chapter 5.html). Factors
* [Try R Chapter 6](Try R tutorial/Try R Chapter 6.html). Files
* [Try R Chapter 7](Try R tutorial/Try R Chapter 7.html). Data Frames

### R Simple Training
#### 3. Charts and Statistics for One Variable
* [Example R 03_01](R Simple Training/Example R 03_01.html).    Creating bar charts for categorical variables
* [Example R 03_02](R Simple Training/Example R 03_02.html).    Creating histograms for quantitative variables
* [Example R 03_03](R Simple Training/Example R 03_03.html).    Creating box plots for quantitative variables
* [Example R 03_04](R Simple Training/Example R 03_04.html).    Calculating frequencies
* [Example R 03_05](R Simple Training/Example R 03_05.html).    Calculating descriptives

#### 4. Modifying Data
* [Example R 04_01](R Simple Training/Example R 04_01.html).	  Recoding variables
* [Example R 04_02](R Simple Training/Example R 04_02.html).    Computing new variables

#### 5. Charts for Associations
* [Example R 05_01](R Simple Training/Example R 05_01.html).	  Creating simple bar charts of group means
* [Example R 05_02](R Simple Training/Example R 05_02.html).    Creating scatterplots
* [Example R 05_03](R Simple Training/Example R 05_03.html).    Creating scatterplot matrices
* [Example R 05_04](R Simple Training/Example R 05_04.html).    Creating 3D scatterplots

#### 6. Statistics for Associations
* [Example R 06_01](R Simple Training/Example R 06_01.html).	  Calculating correlations 
* [Example R 06_02](R Simple Training/Example R 06_02.html).    Computing a regression
* [Example R 06_03](R Simple Training/Example R 06_03.html).    Creating crosstabs for categorical variables
* [Example R 06_04](R Simple Training/Example R 06_04.html).    Comparing means with the t-test
* [Example R 06_05](R Simple Training/Example R 06_05.html).    Comparing means with an analysis of variance (ANOVA)
* [Example R 07_01](R Simple Training/Example R 07_01.html).	  Links

### R Statistics Training
#### 1. Getting Started
* [Example 01_03](R Statistics Training/Example 01_03.html).  		    Taking a first look at the interface			
* [Example 01_04](R Statistics Training/Example 01_04.html).        	Installing and managing packages
* [Example 01_05](R Statistics Training/Example 01_05.html).        	Using built-in datasets in R
* [Example 01_06](R Statistics Training/Example 01_06.html).        	Entering data manually
* [Example 01_07](R Statistics Training/Example 01_07.html).			    Importing data
* [Example 01_08](R Statistics Training/Example 01_08.html).        	Converting tabular data to row data
* [Example 01_09](R Statistics Training/Example 01_09.html).        	Working with color in R
* [Example 01_10](R Statistics Training/Example 01_10.html).        	Exploring color with Colorbrewer
* [Example 01_12](R Statistics Training/Example 01_12_Solution.html).	Solution: Creating color palettes in R

#### 2. Charts for One Variable
* [Example 02_01](R Statistics Training/Example 02_01.html).			      Creating bar charts for categorical variables
* [Example 02_02](R Statistics Training/Example 02_02.html).			      Creating pie charts for categorical variables
* [Example 02_03](R Statistics Training/Example 02_03.html).           	Creating histograms for quantitative variables
* [Example 02_04](R Statistics Training/Example 02_04.html).           	Creating box plots for quantitative variables
* [Example 02_05](R Statistics Training/Example 02_05.html).           	Overlaying plots
* [Example 02_06](R Statistics Training/Example 02_06.html).           	Saving images
* [Example 02_08](R Statistics Training/Example 02_08_Solution.html).  	Solution: Layering plots

#### 3. Statistics for One Variable
* [Example 03_01](R Statistics Training/Example 03_01.html).			      Calculating frequencies
* [Example 03_02](R Statistics Training/Example 03_02.html).           	Calculating descriptives
* [Example 03_03](R Statistics Training/Example 03_03.html).           	Using a single proportion: Hypothesis test and confidence interval
* [Example 03_04](R Statistics Training/Example 03_04.html).           	Using a single mean: Hypothesis test and confidence interval
* [Example 03_05](R Statistics Training/Example 03_05.html).           	Using a single categorical variable: One sample chi-square test
* [Example 03_06](R Statistics Training/Example 03_06.html).           	Examining robust statistics for univariate analyses
* [Example 03_08](R Statistics Training/Example 03_08_Solution.html).  	Solution: Calculating descriptive statistics

#### 4. Modifying Data
* [Example 04_01](R Statistics Training/Example 04_01.html).			      Examining outliers
* [Example 04_02](R Statistics Training/Example 04_02.html).           	Transforming variables
* [Example 04_03](R Statistics Training/Example 04_03.html).           	Computing composite variables
* [Example 04_04](R Statistics Training/Example 04_04.html).           	Coding missing data
* [Example 04_06](R Statistics Training/Example 04_06_Solution.html).  	Solution: Transforming skewed data to pull in outliers

#### 5. Working with the Data File
* [Example 05_01](R Statistics Training/Example 05_01.html).			      Selecting cases
* [Example 05_02](R Statistics Training/Example 05_02.html).           	Analyzing by subgroup
* [Example 05_03](R Statistics Training/Example 05_03.html).           	Merging files
* [Example 05_05](R Statistics Training/Example 05_05_Challenge.html). 	Solution: Analyzing guinea pig data subgroups

#### 6. Charts for Associations
* [Example 06_01](R Statistics Training/Example 06_01.html).			      Creating bar charts of group means
* [Example 06_02](R Statistics Training/Example 06_02.html).           	Creating grouped box plots
* [Example 06_03](R Statistics Training/Example 06_03.html).           	Creating scatter plots
* [Example 06_05](R Statistics Training/Example 06_05_Solution.html).  	Solution: Creating your own grouped box plots

#### 7. Statistics for Associations
* [Example 07_01](R Statistics Training/Example 07_01.html).			      Calculating correlation
* [Example 07_02](R Statistics Training/Example 07_02.html).           	Computing a bivariate regression
* [Example 07_03](R Statistics Training/Example 07_03.html).           	Comparing means with the t-test
* [Example 07_04](R Statistics Training/Example 07_04.html).           	Comparing paired means: Paired t-test
* [Example 07_05](R Statistics Training/Example 07_05.html).           	Comparing means with a one-factor analysis of variance (ANOVA).
* [Example 07_06](R Statistics Training/Example 07_06.html).           	Comparing proportions
* [Example 07_07](R Statistics Training/Example 07_07.html).           	Creating cross tabs for categorical variables
* [Example 07_08](R Statistics Training/Example 07_08.html).           	Computing robust statistics for bivariate associations
* [Example 07_09](R Statistics Training/Example 07_Challenge.html).    	Solution: Comparing proportions across several different groups

#### 8. Charts for Three or More Variables
* [Example 08_01](R Statistics Training/Example 08_01.html).			      Creating clustered bar charts for means			
* [Example 08_02](R Statistics Training/Example 08_02.html).           	Creating scatter plots for grouped data
* [Example 08_03](R Statistics Training/Example 08_03.html).           	Creating scatter plot matrices
* [Example 08_04](R Statistics Training/Example 08_04.html).           	Creating 3D scatter plots
* [Example 08_06](R Statistics Training/Example 08_06_Solution.html).  	Solution: Creating your own scatter plot matrix

#### 9. Statistics for Three or More Variables
* [Example 09_01](R Statistics Training/Example 09_01.html).			      Computing a multiple regression						
* [Example 09_02](R Statistics Training/Example 09_02.html).           	Comparing means with a two-factor ANOVA
* [Example 09_03](R Statistics Training/Example 09_03.html).           	Conducting a cluster analysis
* [Example 09_04](R Statistics Training/Example 09_04.html).           	Conducting a principal components/factor analysis
* [Example 09_06](R Statistics Training/Example 09_06_Solution.html).  	Solution: Creating a cluster analysis of states in the US

### Some R Samples
* [Example 0](R Samples/Settings.html). Settings
* [Example 1](R Samples/Install packages.html). Install packages
* [Example 2](R Samples/Markdown Minimal Example.html). Markdown Minimal Example
* [Example 3](R Samples/DateTime POSIXct Example.html). DateTime POSIXct Example
* [Example 4](R Samples/rCharts JS assets Example.html). rCharts JS assets Example
* [Example 5](R Samples/rCharts rPlot Example.html). rCharts rPlot Example
* [Example 6](R Samples/Google Vis gvisMotionChart Example.html). Google Vis gvisMotionChart Example
