### rCharts Example

### Polychart rPlot
```{r comment = NA, results = 'asis', message = F}
require(rCharts)
## Example 1 Facetted Scatterplot
names(iris) = gsub("\\.", "", names(iris))
r1 <- rPlot(SepalLength ~ SepalWidth | Species, data = iris, color = 'Species', type = 'point')
r1$print('chart1', include_assets = T, cdn = T)

## Example 2 Facetted Barplot
hair_eye = as.data.frame(HairEyeColor)
r2 <- rPlot(Freq ~ Hair | Eye, color = 'Eye', data = hair_eye, type = 'bar')
r2$print('chart2', include_assets = T, cdn = T)
```

```{r comment = NA, results = 'asis', message = F}
#require(rCharts)
#<style>.rChart{width: 600px; height: 400px;}</style>
options(RCHART_WIDTH = 600, RCHART_HEIGHT = 400)
r3 <- rPlot(mpg ~ wt | am + vs, data = mtcars, type = 'point')
r3$print('chart3', include_assets = T, cdn = T)

r4 <- rPlot(mpg ~ wt | am + vs, data = mtcars, type = "point", color = "gear")
r4$print('chart4', include_assets = T, cdn = T)
```



### Data
```{r comment = NA, results = 'asis', message = F}
#install.packages('Lahman')
require(Lahman)  
require(plyr)
dat = Teams[,c('yearID', 'name', 'G', 'SO')]
team_data = na.omit(transform(dat, SOG = round(SO/G, 2)))
league_data = ddply(team_data, .(yearID), summarize, SOG = mean(SOG))
```

### PolyChartsJS
```{r comment = NA, results = 'asis', message = F}
require(rCharts)
#p1 <- rPlot(SOG ~ yearID, data = team_data, type = 'point', 
  #size = list(const = 2), color = list(const = '#888'), 
  #tooltip="function(item){return item.SOG +'\n' + item.name + '\n' + item.yearID}"
#)
p1 <- rPlot(SOG ~ yearID, data = team_data, type = 'point',
            size = list(const = 3), color = list(const = '#888')
            )

p1$print('chart5', include_assets = T, cdn = T)

p1$layer(data = league_data, type = 'line', 
        color = list(const = 'blue'), copy_layer = T, tooltip = NULL)
p1$print('chart6', include_assets = T, cdn = T)

myteam = "Boston Red Sox"
p1$layer(data = team_data[team_data$name == myteam,], color = list(const = 'red'), copy_layer = T)
p1$print('chart7')
```




